#Prokka pathways 
library(tidyr)
library(dplyr)
BiocManager::install("pathview")
library(pathview)
library(RColorBrewer)
library(knitr)

ko <- read.table("concat-high-ko.cleaned.txt") %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(ko = V2)
metat_rpkm <- read.table("high-concat_ORFs_RPKM.csv", sep=',') %>% 
  dplyr::rename(orf = V1) %>% 
  dplyr::rename(rpkm = V2)

prokka_mag_map <- read.table("Prokka_MAG_map (1).csv", header=F, sep=',') %>% 
  dplyr::rename(prokka_id = V1) %>% 
  dplyr::rename(mag = V2)

arc_class <- read.table("gtdbtk.ar122.classification_pplacer.tsv", sep="\t")
bac_class <- read.table("gtdbtk.bac120.classification_pplacer.tsv", sep="\t")
gtdb_dat <- rbind(arc_class, bac_class) %>% 
  dplyr::rename(mag = V1) %>% 
  separate(V2, sep=';', into=c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"))

checkm_dat <- read.table("MetaBAT2_SaanichInlet_135m_min1500_checkM_stdout.tsv",
                         header=TRUE,
                         sep="\t",
                         comment.char = '') %>% 
  dplyr::rename(mag = Bin.Id) %>% 
  dplyr::select(mag, Completeness, Contamination)

# Due to a bug in the renaming script we have to rename the bins. Its a bit hacky but works using tidyverse functions
metag_rpkm <- read.table("SaanichInlet_135m_binned.rpkm.csv", header=T, sep=',') %>% 
  mutate(Sequence = gsub('m_', 'm.', Sequence)) %>% 
  mutate(Sequence = gsub('Inlet_', 'Inlet.', Sequence)) %>% 
  separate(col=Sequence, into=c("mag", "contig"), sep='_', extra="merge") %>% 
  group_by(Sample, mag) %>% 
  summarise(g_rpkm = sum(RPKM)) %>% 
  mutate(mag = gsub('Inlet.', 'Inlet_', mag))

#head(ko) %>% kable()
#head(metat_rpkm) %>% kable()

#gtdb_dat %>% 
  #group_by(Phylum) %>% 
  #summarise(count = n_distinct(mag)) %>% 
  #kable()

gtdb_dat <- dplyr::select(gtdb_dat, mag, Kingdom, Phylum, Class, Order, Family)

rpkm_dat <- left_join(ko, metat_rpkm, by="orf") %>%
  separate(orf, into=c("prokka_id", "orf_id")) %>% # Split the Prokka ORF names into MAG identifier and ORF number for joining
  left_join(prokka_mag_map, by="prokka_id") %>% 
  left_join(gtdb_dat, by="mag") %>% 
  left_join(checkm_dat, by="mag") %>%
  left_join(metag_rpkm, by="mag")

#head(rpkm_dat) %>% kable()

# Subset by taxon
ko_rpkm <- rpkm_dat %>%
  filter(Phylum %in% c("p__Proteobacteria", "p__Nanoarchaeota", "p__Thermoplasmatota")) %>%
  group_by(mag, ko) %>% 
  summarise(t_rpkm = sum(rpkm)) %>% 
  spread(key = mag, value = t_rpkm)

# Subset by completeness and contamination
ko_rpkm <- rpkm_dat %>% 
  filter(Completeness >= 90 & Contamination < 5) %>% 
  group_by(mag, ko) %>% 
  summarise(t_rpkm = sum(rpkm)) %>% 
  spread(key = mag, value = t_rpkm)

# Aggregate by a taxonomy, still summing RPKM of each KO number. You could use mean() instead.
ko_rpkm <- rpkm_dat %>%
  group_by(Class, ko) %>% 
  summarise(t_rpkm = sum(rpkm)) %>% 
  spread(key = Class, value = t_rpkm)

pv_mat <- dplyr::select(ko_rpkm, -ko)
rownames(pv_mat) <- ko_rpkm$ko

# metabolism (which every pathway just change I.D.)
pv.out <- pathview(gene.data = pv_mat,
                   limit = list(gene = c(0,10)),
                   low = list(gene = "#91bfdb"),
                   mid = list(gene = "#ffffbf"),
                   high = list(gene = "#fc8d59"),
                   species = "ko",
                   pathway.id="00190",
                   kegg.dir = "~/Desktop")


